---
apiVersion: v1
kind: Secret
metadata:
  name: wad23-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devhub-test/wad23-backend-gitops
